projects:
  feunote:
    schemaPath: amplify/backend/api/feunote/build/schema.graphql
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: us-west-2
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
